"""removed server defualt for default role

Revision ID: 75b7eca95d3c
Revises: 9cb345eb90d5
Create Date: 2024-02-19 01:29:22.848822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '75b7eca95d3c'
down_revision: Union[str, None] = '9cb345eb90d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
